apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    name: postgres-deploy
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: postgres-deploy
      app: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
      - name: postgres
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"